config/routes.rb
Shoppingcart::Application.routes.draw do
  root :to => "users#login"

  resources :users do
    collection do
      get :login
      post :login
    end
      member do
      get :activate
      get :deactivate
     end
     
  end
resources :users, :products, :orders, :orderlineitems

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderlineitems
  validate :user_id , :presence => true
  validate :order_number, :presence => true
  validates :shipping_address, :presence => true
  validates :billing_address, :presence => true
end

app/models/orderlineitem.rb
class Orderlineitem < ActiveRecord::Base
 belongs_to :orders
#  validates :id, :presence => true
#  validates :quantity, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
# belongs_to :order
# validates :id, :presence => true
  validates :product_cat, :presence => true
  validates :product_sub_cat, :presence => true
  validates :product_name, :presence => true
  validates :product_model, :presence => true
  validates :product_company, :presence => true
  validates :product_stock, :presence => true
  validates :price_per_piece, :presence => true
#  validates :inventory, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :orders
  #  attr_protected :first_name (Wont allow the user enetred field data to store into the database)
  #   attr_readonly :first_name (Wont allow the user Updated data to store into the database)
  #   attribute_for_inspect :first_name
  #   attr_present? :first_name
  #  validates :id, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true
  validates :password, :presence => true
  validates :present_address, :presence => true
  validates :permanent_address, :presence => true
  validates :gender, :presence => true
  validates :dob, :presence => true
  validates :marital_status, :presence => true
  validates :phone_number, :presence => true
  def activate
    self.activate = true
  end
  def deactivate
    self.activate = false
  end
  def self.authenticate(username,password)
    @user = User.find_by_username_and_password(username,password)
#    if self.active == true
#      redirect_to :controller => "products", :action => "new"
#    else
#      redirect_to :controller => "products", :action => "index"
#    end
  end
#  def initialize(attributes={})
#  date_hack(attributes, 'dob')
#  super(attributes)
#end
#
#def date_hack(attributes, property)
#  keys, values = [], []
#  attributes.each_key {|k| keys << k if k =~ /#{property}/ }.sort
#  keys.each { |k| values << attributes[k]; attributes.delete(k); }
#  attributes[property] = values.join("-")
#end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orderlineitems_controller.rb
class OrderlineitemsController < ActionController::Base
layout "application"
  def index
    @olitems = Orderlineitem.all
  end
  def destroy
    @olitem = Orderlineitem.find(params[:id])
    @olitem.destroy
    redirect_to :action => "index"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ActionController::Base
  layout "application"
  def index
    #    render :text => params.inspect and return
    @orders = Order.all
  end
  
  def new
    @order = Order.new
  end

  def create
    #raise params.inspect
  @orders = Order.all
  @products = Product.all
    @order = Order.new(:shipping_address => params[:orders][:shipping_address], :billing_address=>params[:orders][:billing_address])
    @order.user_id = session[:id]
    #   render :text => params.inspect and return
    unless params[:orders][:products].blank?
      @ordered_products =  params[:orders][:products]
      if @order.save
        n = 0
        @ordered_products.each do |product_id|
          product = Product.find product_id.to_i
          order_line_item = @order.orderlineitems.create(:user_id => session[:id], :product_id => product_id, :quantity => params[:orders][:quantity][n])
#          if Stock < 0
#            flash[:notice] = "Your Quantity exceeds the stock"
#            redirect_to :action => "index"
#          end
          stock = product.product_stock.to_i - order_line_item.quantity.to_i 
          product.update_attributes(:product_stock => stock)
          n +=1
        end
        #      flash[:notice] = "You have been Successfully Ordered your products"
        redirect_to :action => "index"
      else
        render :action => "/products/index"
#         flash[:notice] = @order.errors.full_messages
       
      end
    else
      render :action => "/products/index"
    end

  end

  def edit
    @order = Order.find(params[:id])
  end
  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to :action => "index"
    else
      render :action =>"edit"
    end
  end
  def show
    @order = Order.find(params[:id])
  end
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to :action => "index"
  end
end

app/controllers/products_controller.rb
class ProductsController < ActionController::Base
  layout "application"
  def index
    @products = Product.all
  end
  def new
    
    @product = Product.new
  end
  def create
    @product = Product.new(params[:product])
    if
      @product.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to :action => "index"
    else
      render :action =>"edit"
    end
  end
  def show
    @product = Product.find(params[:id])
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to :action => "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  layout "application"
  def index
    @users = User.all
    #    raise response.inspect
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    #@user.dob = Date.civil(params[:user][:"dob(1i)"].to_i,params[:user][:"dob(2i)"].to_i,params[:user][:"dob(3i)"].to_i)
    if @user.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to :action => "show"
    else
      render :action => "edit"
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def activate
    #    raise params[:id].inspect
    @user= User.find(params[:id])
    @user.update_attribute(:active,true)
    redirect_to :action => "index"
  
  end
   def deactivate
    #    raise params[:id].inspect
    @user= User.find(params[:id])
    @user.update_attribute(:active,false)
    redirect_to :action => "index"

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :action => "index"
  end

  def login
    # render :text => "hi" and return
    #  raise params.inspect
    if request.post?
#         raise params.inspect
      user = User.authenticate(params[:username], params[:password])   
#    if params[:username] == "admin" && params[:password] == "admin"
#    redirect_to :controller => "products", :action => "new"
#    end

      if user
         # raise session.inspect
        session[:id] = user.id
        flash[:notice] = "You are now successfully logged in."
        redirect_to(:controller => "products", :action => "index")
      else 
#           raise params.inspect
        flash[:notice] = "Invalid User name or Password combination"
        render("login" )
      end
    end
  end
  
  def logout
#     raise session.inspect
    session[:id]=nil
    flash[:notice] = "You have been logged out."
    redirect_to(:action=>"login")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppingcart</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orderlineitems/_form.html.erb
<table border ="1" bgcolor="AliceBlue">
  <tr bgcolor="black">
    <td colspan="2"><div><%= link_to "Sign Out",:controller => "users", :action => "login"%></div><center><font color="white"><b>USER ORDER FORM</b></font></center></td>
  </tr>
  <tr>
  <td>User Id</td>
  <td><%= f.text_field :f.text_field :user_id %></td>
</tr>
<tr>
  <td>Order Id</td>
  <td><%= f.text_field :f.text_field :order_id %></td>
</tr>
<tr>
  <td>Product Id</td>
 <td><%= f.text_field :f.text_field :product_id %></td>
</tr>
<tr>
  <td>Quantity</td>
 <td><%= f.text_field :f.text_field :quantiy %></td>
</tr>
    <tr bgcolor="black">
      <td colspan="2">
        <center> <%= f.submit "Save" %>
  <%= f.submit("Reset", {:name => 'reset' ,:type => "reset" }) %></center>
      </td>
    </tr>
</table>

app/views/orderlineitems/index.html.erb
<body bgcolor="black">
    <%= stylesheet_link_tag "applyme" %>
<center>
  <table border ="1" bgcolor="AliceBlue" style="margin-top: 100px;">
    <tr bgcolor="black">
    <td colspan="6"><center><font color="white"><b>ORDERS LINE ITEMS</b></font></center></td>
    </tr>
  <tr bgcolor="black">
    <td><font color="white">Si No</font></td>
    <td><font color="white">User Id</font></td>
    <td><font color="white">OrderId</font></td>
    <td><font color="white">Product Id</font></td>
    <td><font color="white">Quantity</font></td>
    <td><font color="white"><center>Action</center></font></td>
  </tr>
  <% for olitem in @olitems %>
    <tr>
      <td><center><%= olitem.id %></center></font></td>
      <td><%= olitem.user_id %></td>
      <td><%= olitem.order_id %></td>
      <td><%= olitem.product_id %></td>
      <td><%= olitem.quantity %></td>
      <td bgcolor="LightSlateGray"><%= link_to("Delete", orderlineitem_path(olitem.id), :method => :delete, :confirm => "Are you sure to delete this record?") %> |
            <%= link_to "Edit", edit_orderlineitem_path(olitem) %> |
            <%= link_to "Show", orderlineitems_path(olitem) %></td>
    </tr>
    <% end %>
     <tr bgcolor="black">

        <td colspan="11"><font color="white"><b><center><%= "Number of Users Ordered :" %> <font color="yellow"><%= @olitems.count %></font></center></b></font></td>
      </tr>
</table>
</center>
</body>

app/views/orders/_form.html.erb
<table border ="1" bgcolor="AliceBlue">
  <tr bgcolor="black">
    <td colspan="2"><div><%= link_to "Sign Out",:controller => "users", :action => "login"%></div><center><font color="white"><b>USER ORDER FORM</b></font></center></td>
  </tr>
  <%#*<tr>%>
    <%#*<td>Order Number</td>%>
    <%#*<td><%= f.text_field :order_number %>
  <%#*</tr>%>
  <%#*<tr>%>
    <%#*<td>User Id</td>%>
    <%#*<td><%= f.text_field :user_id %>
  <%#*</tr>%>
  <tr>
  <td>Shipping Address</td>
  <td><%= f.text_area :shipping_address, :rows => 3, :cols => 35  %></td>
</tr>
<tr>
  <td>Billing Address</td>
  <td><%= f.text_area :billing_address, :rows => 3, :cols => 35  %></td>
</tr>
    <tr bgcolor="black">
      <td colspan="2">
        <center> <%= f.submit "Save" %>
  <%= f.submit("Reset", {:name => 'reset' ,:type => "reset" }) %></center>
      </td>
    </tr>
</table>

app/views/orders/edit.html.erb
<body bgcolor="black">
<center>
  <br /><br />
  <font size= "5px" color="white"><%= "Dear!" %> </font> <font color="yellow" size ="4"><b><%= "Admin" %></b></font>  <font size= "4px" color="white"><%= "Please Update Your Product Details..." %></font>
<table border="1"  style="margin-top: 60px;" bgcolor="AliceBlue">
 <%= form_for @order do |f| %>
  <tr bgcolor="black">
    <td colspan="3"><font color="white"><b><center>ORDER DETAILS</center></b></font></td>
  </tr>
   <%#*<tr>%>
    <%#*<td>Order Number</td>%>
    <%#*<td><%= f.text_field :order_number %>
  <%#*</tr>%>
  <%#*<tr>%>
    <%#*<td>User Id</td>%>
    <%#*<td><%= f.text_field :user_id %>
  <%#*</tr>%>
  <tr>
  <td>Shipping Address</td>
  <td><%= f.text_area :shipping_address,:rows => 3, :cols => 35 %></td>
</tr>
<tr>
  <td>Billing Address</td>
  <td><%= f.text_area :billing_address, :rows => 3, :cols => 35 %></td>
</tr>
  <tr bgcolor="black">
        <td colspan="3">
          <center> <%= f.submit "Update" %>
            <%= f.submit("Reset",{:name => 'reset' ,:type => "reset"}) %></center>
        </td>
      </tr>
      <% end %>
</table>
</center>
</body>

app/views/orders/index.html.erb
<body bgcolor="black">

  <%= stylesheet_link_tag "applyme" %>
  <center>
    <table border ="1" bgcolor="AliceBlue" style="margin-top: 100px;">
      <tr bgcolor="black">
        <td colspan="6"><center><font color="white"><b>ORDERS LIST</b></font></center></td>
      </tr>
      <tr bgcolor="black">
        <td><font color="white">Order Id</font></td>
        <td><font color="white">Order Number</font></td>
        <td><font color="white">User Id</font></td>
        <td><font color="white">Shipping Address</font></td>
        <td><font color="white">Billing Address</font></td>
        <td><font color="white"><center>Action</center></font></td>
      </tr>
      <% for order in @orders %>
  <%#=  raise @orders.inspect %>
        <tr>
          <td><center><%= order.id %></center></font></td>
          <td><%= order.order_number %></td>
          <td><%= order.user_id %></td>
          <td><%= order.shipping_address %></td>
          <td><%= order.billing_address %></td>
          <td bgcolor="LightSlateGray "><%= link_to("Delete", order_path(order.id), :method => :delete, :confirm => "Are you sure to delete this record?") %> |
            <%= link_to "Edit", edit_order_path(order) %> |
            <%= link_to "Show", order_path(order) %> |
          <%= link_to "Order Line Items", :controller=> "orderlineitems", :action => "index" %></td>
        </tr>
      <% end %>
      <tr bgcolor="black">

        <td colspan="11"><font color="white"><b><center><%= "Number of Users Ordered :" %> <font color="yellow"><%= @orders.count %></font></center></b></font></td>
      </tr>
    </table>
  </center>
</body>

app/views/orders/new.html.erb
<br /><br />
<body bgcolor="black">
   <%= stylesheet_link_tag "applyme" %>
<center>
  <font color="white" size="5"><b><%= "Dear" %></b> </font> <font color="yellow" size="4"><%= "User" %> </font> <font color="white" size="4"><%= "Please Create Your Orders Here..." %></font>
  <br /><br /><br /><br />
<div id="order">
<% form_for @order do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
  <%end%>
</div>
</center>
</body>

app/views/orders/show.html.erb
<body bgcolor="black">
<center>
   <%= stylesheet_link_tag "applyme" %>
  <br />
  <font size= "5px" color="white"><%= "Dear!" %> </font> <font color="yellow"><b><%= "User" %></b></font>  <font size= "4px" color="white"><%= "Please Verify Your Order Details..." %></font>
  <br />
  <br />
  <br />
  <table border="1" bgcolor="AliceBlue">
    <tr bgcolor="black">
      <td colspan="3"><font color="white"><b><center>USERS ORDERS INFORMATION</center></b></font></td>
    </tr>
    <tr>
      <td>Order Number</td>
      <td><%= @order.order_number %></td>
    </tr>
    <tr>
      <td>User Id</td>
      <td><%= @order.user_id %></td>
    </tr>
    <tr>
      <td>Shipping Address</td>
      <td><%= @order.shipping_address %></td>
    </tr>
    <tr>
      <td>Billing Address</td>
      <td><%= @order.billing_address %></td>
    </tr>
    <tr bgcolor="black">
      <td colspan="2" class="rightalign">
        <div class="left-align"><%= link_to "Orders List", :action => "index" %></div>
       <%= link_to "Edit", edit_order_path(@order) %>
      </td>
    </tr>
  </table>
</center>
</body>

app/views/products/_form.html.erb
<table border ="1" bgcolor="AliceBlue">
  <tr bgcolor="black">
    <td colspan="2"><center><font color="white"><b>PRODUCTS FORM</b></font></center></td>
  </tr>
  <tr>
    <td>Product Category</td>
    <td><%= f.select :product_cat, options_for_select([["select",""],["Mobiles","1"],["Televisions","2"],["Refrigerators","3"],["Home Theaters","4"],["DVD / CD","5"],["Kitchen","6"]]) %></td>

    <%#*<td><%= f.text_field :product_cat %>
  </tr>
   <tr>
    <td>Product Sub Category</td>
    <%#= f.select :product_sub_cat, options_for_select(%w(Nokia Samsung Lg Sony_Ericsson Micromax Onida)) %>
     <td><%= f.select :product_sub_cat, options_for_select([["select",""],["Nokia","1"],["Samsung","2"],["Lg","3"],["Sony_Ericsson","4"],["Micromax","5"],["Onida","6"]]) %></td>
    

    <%#*<td><%= f.text_field :product_sub_cat %>
  </tr>
    <tr>
    <td>Product Name</td>
    <%#= f.select :product_name, options_for_select(%w(Led Lcd Normal Ordinary Monochrome Color SmartPhone), {:prompt => "select"}) %>
    <td><%= f.select :product_name, options_for_select([["select",""],["LED","1"],["LCD","2"],["Color","3"],["Monochrome","4"],["Smart Phone","5"]]) %></td>
  </tr>
    <tr>
  <td>Product Model</td>
   <%#= f.select :product_model, options_for_select(%w(5233 5230 2630 1102 5102 5211)) %>
    <td><%= f.select :product_model, options_for_select([["select",""],["5233","1"],["5230","2"],["2630","3"],["1102","4"],["5102","5"],["5211","6"]]) %></td>
  </tr>
   <tr>
    <td>Company</td>
    <%#*<td><%= f.text_field :product_company %>
    <td><%= f.select :product_company, options_for_select([["select",""],["Nokia","1"],["Samsung","2"],["Lg","3"],["Sony_Ericsson","4"],["Micromax","5"],["Onida","6"]]) %></td>
  </tr>
    <tr>
    <td>Available Stock</td>
    <td><%= f.text_field :product_stock %></td>
  </tr>
   <tr>
    <td>Price Per Piece</td>
    <td><%= f.text_field :price_per_piece %></td>
  </tr>
   <tr>
 <td colspan="2" bgcolor="black">
     <center><%=  f.submit "Save" %>
  <%= f.submit("Reset", {:name => 'reset' ,:type => "reset" }) %></center>
      </td>
    </tr>
</table>

app/views/products/edit.html.erb
<body bgcolor="black">
<center>
  <br /><br />
  <font size= "5px" color="white"><%= "Dear!" %> </font> <font color="yellow" size ="4"><b><%= "Admin" %></b></font>  <font size= "4px" color="white"><%= "Please Update Your Product Details..." %></font>
<table border="1"  style="margin-top: 60px;" bgcolor="AliceBlue">
 <%= form_for @product do |f| %>
  <tr bgcolor="black">
    <td colspan="3"><font color="white"><b><center>PRODUCT DETAILS</center></b></font></td>
  </tr>
   <tr>
    <td>Product Category</td>
    <td><%= f.text_field :product_cat %></td>
  </tr>
   <tr>
    <td>Product Sub Category</td>
    <td><%= f.text_field :product_sub_cat %></td>
  </tr>
    <tr>
    <td>Product Name</td>
    <td><%= f.text_field :product_name %></td>
  </tr>
    <tr>
  <td>Product Model</td>
    <td><%= f.text_field :product_model %></td>
  </tr>
   <tr>
    <td>Company</td>
    <td><%= f.text_field :product_company %></td>
  </tr>
    <tr>
    <td>Available Stock</td>
    <td><%= f.text_field :product_stock %></td>
  </tr>
   <tr>
    <td>Price Per Piece</td>
    <td><%= f.text_field :price_per_piece%></td>
   </tr>
  <tr bgcolor="black">
        <td colspan="3">
          <center> <%= f.submit "Update" %>
            <%= f.submit("Reset",{:name => 'reset' ,:type => "reset"}) %></center>
        </td>
      </tr>
      <% end %>
</table>
</center>
</body>

app/views/products/index.html_1.erb
<body bgcolor="black">
    
<center>
  <table border ="1" bgcolor="AliceBlue" style="margin-top: 100px;">
    <tr bgcolor="black">
    <td colspan="9"><center><font color="white"><b>PRODUCT LIST</b></font></center></td>
    </tr>
  <tr bgcolor="black">
    <td><font color="white">Id</font></td>
    <td><font color="white">Category </font></td>
    <td><font color="white">Sub Category</font></td>
    <td><font color="white">Type</font></td>
    <td><font color="white">Model</font></td>
    <td><font color="white">Company</font></td>
    <td><font color="white">Stock</font></td>
    <td><font color="white">Price Per Product</font></td>
    
    <td><font color="white"><center>Action</center></font></td>
  </tr>
  <% for products in @products %>
    <tr>
      <td><center><%= products.id %></center></font></td>
      <td><%= products.product_cat %></td>
      <td><%= products.product_sub_cat %></td>
      <td><%= products.product_name %></td>
      <td><%= products.product_model %></td>
      <td><%= products.product_company %></td>
      <td><%= products.product_stock %></td>
      <td><%= products.price_per_piece %></td>
      <td bgcolor="LightSlateGray "><%= link_to("Delete",product_path(products), :method => :delete, :confirm => "Are you sure to delete this Product ?") %> |
            <%= link_to "Edit", edit_product_path(products) %> |
            <%= link_to "Show", product_path(products) %></td>
    </tr>
    <% end %>
     <tr bgcolor="black">

        <td colspan="11"><font color="white"><b><center><%= "Number of products added :" %> <font color="yellow"><%= @products.count %></font></center></b></font></td>
      </tr>
</table>
</center>
</body>

app/views/products/show.html.erb
<body bgcolor="black" style="margin-top: 100px;">
  <center><font size= "5px" color="white"><%= "Dear!" %> </font> <font color="yellow" size ="4"><b><%= "Admin" %></b></font>  <font size= "4px" color="white"><%= "Please Verify Your Product Details..." %></font></center>
<center>
  <table border="1" bgcolor="AliceBlue" style="margin-top: 50px;">
  <tr bgcolor="black">
    <td colspan="3"><font color="white"><b><center>PRODUCT DETAILS</center></b></font></td>
  </tr>
  <tr>
    <td>Si No</td>
    <td><font color="black"><%= @product.id %></td>
  </tr>
  <tr>
    <td>Category</td>
    <td><font color="black"><%= @product.product_cat %></td>
  </tr>
  <tr>
    <td>Sub Category</td>
    <td><font color="black"><%= @product.product_sub_cat %></td>
  </tr>
  <tr>
    <td>Name</td>
    <td><font color="black"><%= @product.product_name %></td>
    </tr>
   <tr>
    <td>Model</td>
    <td><font color="black"><%= @product.product_model %></td>
  </tr>
   <tr>
    <td>Company</td>
    <td><font color="black"><%= @product.product_company %></td>
  </tr>
   <tr>
    <td>Available Stock</td>
    <td><font color="black"><%= @product.product_stock %></td>
  </tr>
   <tr>
    <td>Price Per Piece</td>
    <td><font color="black"><%= @product.price_per_piece %></td>
  </tr>
   <tr bgcolor="black">
      <td colspan="2" class="rightalign">
        <div class="left-align"><%= link_to "Products List", :action => "index"%></div>
        <%= link_to "Edit", edit_product_path(@product)%>
      </td>
    </tr>
</table>
</center>
</body>

app/views/users/index.html.erb
<body bgcolor="black">
  <center>
    <table border ="1" bgcolor="AliceBlue" style="margin-top: 100px;">
      <tr bgcolor="black">
        <td colspan="11"> <div class="left-align"><fontcolr="white"> <%=link_to("Sign out",{:action=>'login'}) %></font></div><div><font color="yellow"><b>&nbsp;&nbsp;<%= flash[:notice] %></b></font></div><center><div><font color="white"><b>USERS LIST</b></font></div></td>
      </tr>
      <tr bgcolor="black">
        <td><font color="white">User Id</font></td>
        <td><font color="white">Fisrt Name</font></td>
        <td><font color="white">Last Name</font></td>
        <td><font color="white">Present Address</font></td>
        <td><font color="white">Permanent Address</font></td>
        <td><font color="white">Gender</font></td>
        <td><font color="white">Date of birth</font></td>
        <td><font color="white">Marital Status</font></td>
        <td><font color="white">Phone Number</font></td>
        <td><font color="white">Activation</font></td>
        <td><font color="white">Action</font></td>
      </tr>
      <% for user in @users%>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.present_address %></td>
          <td><%= user.permanent_address %></td>
          <td><%= user.gender %></td>
          <td><%= user.dob %></td>
          <td><%= user.marital_status %></td>
          <td><%= user.phone_number %></td>
          <td colospan="2" bgcolor="LightSlateGray">
            <center><%= link_to "Active", activate_user_path(user.id) %>
              <%= link_to "Deactive", deactivate_user_path(user.id) %></center></td>
          <td bgcolor="LightSlateGray"><%= link_to("Delete",user_path(user), :method => :delete, :confirm => "Are you sure to delete this record?") %> |
            <%= link_to "Edit", edit_user_path(user) %> |
            <%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
      <tr bgcolor="black">

        <td colspan="11"><font color="white"><b><center><%= "Number of users registered :" %> <font color="yellow"><%= @users.count %></font></center></b></font></td>
      </tr>
    </table>
  </center>
</body>

app/views/users/show.html.erb
<body bgcolor="black">
<center>
  <br />
  <font size= "5px" color="white"><%= "Dear!" %> </font> <font color="yellow"><b><%= "#{@user.first_name.upcase}  #{@user.last_name.upcase}"%></b></font>  <font size= "4px" color="white"><%= "Please Verify Your Account Details..." %></font>
  <br />
  <br />
  <br />
  <table border="1" bgcolor="AliceBlue">
    <tr bgcolor="black">
      <td colspan="3"><font color="white"><b><center>USERS INFORMATION</center></b></font></td>
    </tr>
    <tr>
      <td>Si No.</td>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <td>First Name</td>
      <td><%= @user.first_name %></td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <td>User Name</td>
      <td><%= @user.username %></td>
    </tr>
    <tr>
      <td>Password</td>
      <td><%= @user.password %></td>
    </tr>
    <tr>
      <td>Present Address</td>
      <td><%= @user.present_address %></td>
    </tr>
    <tr>
      <td>Permanent Address</td>
      <td><%= @user.permanent_address %></td>
    </tr>
    <tr>
      <td>Gender</td>
      <td><%= @user.gender %></td>
    </tr>
     <tr>
      <td>Date of birth</td>
      <td><%= @user.dob %></td>
    </tr>
    <tr>
      <td>Marital Status</td>
      <td><%= @user.marital_status %></td>
    </tr>
    <tr>
      <td>Phone Number</td>
      <td><%= @user.phone_number %></td>
    </tr>
    <tr bgcolor="black">
      <td colspan="2" class="rightalign">
        <div class="left-align"><%= link_to "Users List", :action => "index"%></div>
       <%= link_to "Edit", edit_user_path(@user) %>
      </td>
    </tr>
  </table>
</center>
</body>